server:
  port: 8082
#SSL
#  ssl:
#    key-store: classpath:ssl/keystore.p12
#    key-store-password: egoo3466
#    key-store-type: PKCS12
#    key-alias: tomcat



#热部署
#spring:
#  devtools:
#    restart:
#      additional-paths=src/main/java,src/main/resources

swagger-url: http://127.0.0.1:8082

para: aaaaaaaaaaaaaaaaaa
para2: aaaaaaazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz


