
mybatis:
  url: jdbc:mysql://localhost:3306/mybatis
  username: root
  password: root
  maxActive: 500
  driver: com.mysql.jdbc.Driver
#
#mybatis.url6=jdbc:mysql://localhost:3306/mybatis2
#mybatis.username6=root
#mybatis.password6=root
#mybatis.maxActive6=500