
spring:
  datasource:
    db1:
      url: jdbc:mysql://X.X.X.X:port/titan?characterEncoding=UTF-8
      username:
      password:
      driver-class-name: com.mysql.jdbc.Driver
    db2:
      url: jdbc:mysql://X.X.X.X:port/titan2?characterEncoding=UTF-8
      username:
      password:
      driver-class-name: com.mysql.jdbc.Driver